%YAML 1.1
---
# Snapcraft Recipe for gallery-dl
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: gallery-dl
license: GPL-2.0
base: core18
summary: Download image-galleries and -collections from several image hosting sites
description: |
  `gallery-dl` is a command-line program to download image-galleries and -collections from several image hosting sites (see [Supported Sites](https://github.com/mikf/gallery-dl/blob/master/docs/supportedsites.rst)). It is a cross-platform tool with many configuration options and powerful filenaming capabilities.

adopt-info: gallery-dl
confinement: strict
grade: stable

plugs:
  # For `xdg-open` command access for opening OAuth authentication webpages
  desktop:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Network access
  network:

  # For network service for recieving OAuth callback tokens
  network-bind:

  # Configuration access
  personal-files:
    read:
    - $HOME/.config/gallery-dl
    - $HOME/.gallery-dl.conf
  system-files:
    read:
    - /etc/gallery-dl.conf

parts:
  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/

  # Check out the tagged release revision if it isn’t promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout

  gallery-dl:
    after:
    - selective-checkout

    source: .
    override-pull: |
      snapcraftctl pull
      $SNAPCRAFT_STAGE/scriptlets/selective-checkout

    plugin: python
    build-packages:
    - make
    python-packages:
    - youtube_dl
    override-build: |
      # build manpages and bash completion
      make man completion

      snapcraftctl build

  ffmpeg:
    plugin: nil
    stage-snaps:
    - ffmpeg-core18-lgpl
    stage-packages:
    ### Dynamic-linking safe dependencies
    - libasound2
    - libass9
    - libbluray2
    - libbs2b0
    - libcaca0
    - libdrm2
    - libfontconfig1
    - libfribidi0
    - libgmp10
    - libgraphite2-3
    - libharfbuzz0b
    - libmp3lame0
    - try:
      - libnuma1
    - libogg0
    - libopencore-amrnb0
    - libopencore-amrwb0
    - libopus0
    - libslang2
    - libtheora0
    - libva-drm2
    - libva-x11-2
    - libva2
    - libvdpau1
    - libvo-amrwbenc0
    - libvorbis0a
    - libvorbisenc2
    - libvpx5
    - libx11-6
    - libxau6
    - libxcb-shape0
    - libxcb-shm0
    - libxcb-xfixes0
    - libxdmcp6
    - libxext6
    - libxfixes3

apps:
  gallery-dl:
    adapter: full
    command-chain:
    - bin/gallery-dl-launch
    command: bin/gallery-dl
    completer: etc/bash_completion.d/gallery-dl.bash_completion
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

      # Satisfy FFmpeg's libpulsecommon dependency
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
